server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlserver://192.168.3.14;databaseName=SBODemoCN
    username: sa
    password: avatech
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
              ddl-auto: none
              show-sql: true
logging:
  level:
    org:
      hibernate:
              SQL: DEBUG


